# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

# ===================================================================
# Specific application properties.
# ===================================================================
rpm:
  iam:
    activation:
      jwt:
        secret: ${RPM_IAM_ACTIVATION_JWT_SECRET}
