name: rpm-ddd
services:
  postgres:
    extends:
      file: postgres.yml
      service: postgres

  mailpit:
    image: axllent/mailpit:v1.21.8
    container_name: rpm-ddd-mailpit
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    ports:
      - "1025:1025"
      - "8025:8025"
